version: '3'
services:
  web:
    image: pbadhe34/my-apps:user-app

##pbadhe34/my-apps:user-app-pod
    ports:
       - "8090"
    networks:
       - webnet     
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  localhost:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "MyRootPass123"
      MYSQL_DATABASE: userservice
      MYSQL_USER: app-user
      MYSQL_PASSWORD: "MyRootPass123"
    volumes:
       - "/mysql/data:/var/lib/mysql"
    networks:
       - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet 
networks:
  webnet:
