version: '3'
services: 

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "MyRootPass123"
      MYSQL_DATABASE: userservice
      MYSQL_USER: app-user
      MYSQL_PASSWORD: "MyRootPass123"
    volumes:
       - "/mysql/data:/var/lib/mysql"
    networks:
       - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
   
networks:
  webnet:
