version: '3.1'
services:
  
 app1:
    image: mysql:5.6
    environment:
#The MYSQL_ROOT_PASSWORD with secret value  doesnot work
#The passowrd value is taken as "/run/secrets/pass"
#Use MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/pass" with NEW Empty Volume directory to crdate the new root user record.
#The MYSQL_ROOT_PASSWORD_FILE: "/run/secrets will not work with existing volumes


      MYSQL_ROOT_PASSWORD: /run/secrets/pass
      MYSQL_PASSWORD: /run/secrets/pass
      MYSQL_USER: ashok
      MYSQL_DATABASE: appuser
    volumes:
       - "/app/data:/var/lib/mysql"
    secrets:
       - pass
    networks:
       - test
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
       condition: on-failure
secrets:
  pass:
    external: true
networks:
  test:
