version: '3.1'
services:
  
 app-mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/pass"
      MYSQL_PASSWORD_FILE: "/run/secrets/pass"
      MYSQL_USER: ashok
      MYSQL_DATABASE: appuser
    volumes:
       - "/app/test:/var/lib/mysql"
    secrets:
       - pass
    networks:
       - webnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
       condition: on-failure
secrets:
  pass:
    external: true
networks:
  webnet:
